[[custom_groups]]
name = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
type = "select"
rule = ["[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]ğŸ¯ å…¨çƒç›´è¿",  "[]ğŸ‡²ğŸ‡´ Macau", "[]ğŸ‡¹ğŸ‡¼ Taiwan", "[]ğŸ‡¹ğŸ‡¼ Taiwan BGP", "[]ğŸ‡­ğŸ‡° Hong Kong", "[]ğŸ‡­ğŸ‡° Hong Kong BGP", "[]ğŸ‡­ğŸ‡° Hong Kong IEPL", "[]ğŸ‡¯ğŸ‡µ Japan", "[]ğŸ‡°ğŸ‡· South Korea", "[]ğŸ‡¸ğŸ‡¬ Singapore"]

[[custom_groups]]
name = "å¼ºåˆ¶é€‰æ‹©"
type = "select"
rule = [".*"]

[[custom_groups]]
name = "osu!"
type = "select"
rule = ["[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©", "[]å¼ºåˆ¶é€‰æ‹©", "[]ğŸ¯ å…¨çƒç›´è¿", "[]ğŸ‡²ğŸ‡´ Macau"]

[[custom_groups]]
name = "Discord"
type = "select"
rule = ["[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©", "[]å¼ºåˆ¶é€‰æ‹©", "[]ğŸ¯ å…¨çƒç›´è¿", "[]ğŸ‡­ğŸ‡° Hong Kong", "[]ğŸ‡­ğŸ‡° Hong Kong BGP", "[]ğŸ‡­ğŸ‡° Hong Kong IEPL", "[]ğŸ‡¯ğŸ‡µ Japan", "[]ğŸ‡¸ğŸ‡¬ Singapore"]

[[custom_groups]]
name = "Uma Musume"
type = "select"
rule = ["[]ğŸ‡¯ğŸ‡µ Japan"]

[[custom_groups]]
name = "Temporary"
type = "select"
rule = ["[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©", "[]å¼ºåˆ¶é€‰æ‹©", "[]ğŸ¯ å…¨çƒç›´è¿"]

[[custom_groups]]
name = "ğŸ‡²ğŸ‡´ Macau"
type = "url-test"
rule = ["(MO|Macau|Macao|æ¾³é—¨|CTM|æ¾³é–€)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡­ğŸ‡° Hong Kong"
type = "url-test"
rule = ["(?i:HK|Hong.*?Kong|HKT|HKBN|HGC|WTT|CMI|[^-]æ¸¯)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡­ğŸ‡° Hong Kong BGP"
type = "url-test"
rule = ["(é¦™æ¸¯.* BGP|ä¸­æ¸¯.* BGP)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡­ğŸ‡° Hong Kong IEPL"
type = "url-test"
rule = ["(é¦™æ¸¯.* IEPL|ä¸­æ¸¯.* IEPL)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡¹ğŸ‡¼ Taiwan"
type = "url-test"
rule = ["(Taiwan|æ–°åŒ—|å½°åŒ–|CHT|å°æ¹¾|[^-]å°|HINET)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡¹ğŸ‡¼ Taiwan BGP"
type = "url-test"
rule = ["(å°æ¹¾.* BGP)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡¯ğŸ‡µ Japan"
type = "url-test"
rule = ["(JP|Japan|æ—¥æœ¬|ä¸œäº¬|å¤§é˜ª|åŸ¼ç‰|[^-]æ—¥)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡°ğŸ‡· South Korea"
type = "url-test"
rule = ["(?i:KR|Korea|KOR|é¦–å°”|éŸ©|éŸ“)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ Singapore"
type = "url-test"
rule = ["(?i:SG|Singapore|æ–°åŠ å¡|ç‹®åŸ|[^-]æ–°)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ¥ NETFLIX"
type = "select"
rule = [
    "[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
    "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©",
    "[]ğŸ¯ å…¨çƒç›´è¿",
    ".*"
]

[[custom_groups]]
name = "â›”ï¸ å¹¿å‘Šæ‹¦æˆª"
type = "select"
rule = ["[]ğŸ›‘ å…¨çƒæ‹¦æˆª",
"[]ğŸ¯ å…¨çƒç›´è¿",
"[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
]

[[custom_groups]]
name = "ğŸš« è¿è¥åŠ«æŒ"
type = "select"
rule = ["[]ğŸ›‘ å…¨çƒæ‹¦æˆª",
"[]ğŸ¯ å…¨çƒç›´è¿",
"[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©"]

[[custom_groups]]
name = "ğŸŒ å›½å¤–åª’ä½“"
type = "select"
rule = ["[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
"[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©",
"[]ğŸ¯ å…¨çƒç›´è¿",
".*"]

[[custom_groups]]
name = "ğŸŒ å›½å†…åª’ä½“"
type = "select"
rule = ["[]ğŸ¯ å…¨çƒç›´è¿",
"(HGC|HKBN|PCCW|HKT|æ·±å°|å½°åŒ–|æ–°åŒ—|å°|hk|æ¸¯|tw)",
"[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©"]

[[custom_groups]]
name = "â“‚ï¸ å¾®è½¯æœåŠ¡"
type = "select"
rule = ["[]ğŸ¯ å…¨çƒç›´è¿",
"[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
".*"]

[[custom_groups]]
name = "ğŸ“² ç”µæŠ¥ä¿¡æ¯"
type = "select"
rule = ["[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
"[]ğŸ¯ å…¨çƒç›´è¿",
".*"]

[[custom_groups]]
name = "ğŸ è‹¹æœæœåŠ¡"
type = "select"
rule = ["[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
"[]ğŸ¯ å…¨çƒç›´è¿",
"[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©",
".*"]

[[custom_groups]]
name = "ğŸ¯ å…¨çƒç›´è¿"
type = "select"
rule = ["[]DIRECT"]

[[custom_groups]]
name = "ğŸ›‘ å…¨çƒæ‹¦æˆª"
type = "select"
rule = ["[]REJECT", "[]DIRECT"]

[[custom_groups]]
name = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
type = "select"
rule = ["[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
"[]ğŸ¯ å…¨çƒç›´è¿",
"[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©",
".*"]

[[custom_groups]]
name = "â™»ï¸ è‡ªåŠ¨é€‰æ‹©"
type = "url-test"
rule = [".*"]
url = "http://www.gstatic.com/generate_204"
interval = 300